### ISSUE TITLE
Bank account list should take operationId into account

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#105]
Currently, the request for getting list of bank accounts only takes userId. This does not always work - we need to be able to determine the form data based on operationId as well.

For example, payment may already have source account, hence we should not be showing the account selection...

**Comment by romanstrobl** [comment]
Another change we discussed is that the request should be more generic - e.g. getDynamicFormData() instead of getBankAccountList().

**Comment by petrdvorak** [comment]
Yes, issue #106 is exactly about this.
