### ISSUE TITLE
Better abstraction of "BankAdapter"

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#106]
Currently, bank adapter seems too "bank specific" (too strongly bound with given domain) - I know the name incorrectly suggest it, but we should fix it. From Web Flow perspective, "Bank Adapter" should be simply an URL configuration, without strong model dependencies.

Btw this was the whole point of isolating bank adapter - to have one API on output for all domains (banking, telco, pharmaceutics, ...) and have internal business logics that is domain specific...

**Comment by romanstrobl** [comment]
See also #111 - renaming is the first change leading to generalization of Bank Adapter.

**Comment by romanstrobl** [comment]
Closing issue, we generalized most of bank domain specific code.
