### ISSUE TITLE
Store `salt` from DataDigest object when generating SMS OTP

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#115]
Instead of using just data digest from the cryptographic routine, we should work with both `digest` and `salt`, in following way:

- We should store `salt` in the database, alongside the data.
- We should send `digest` into SMS message.
- We can also store `digest` and SMS message text in the database, and work with it as we do it now...

Simply put, we need to have the `salt` store somewhere in order to provide a proof of how the digest was actually computed...

**Comment by romanstrobl** [comment]
Ok, let's store the salt in the database, I will add a column.
