### ISSUE TITLE
Error handling when push notification fails

### ISSUE THREAD

**Issue by romanstrobl** [lime-company/powerauth-webflow#125]
We should handle the case when push notification fails. As part of #120 the push notification error is exposed, however the user is redirected due to an error. The redirect interrupts the workflow and cancels the operation.

**Comment by petrdvorak** [comment]
We should silently ignore this error, as if the push message didn't arrive for any other reason (for example, error between Apple and user device).

**Comment by romanstrobl** [comment]
Ok, fixed as part of pull request #124
