### ISSUE TITLE
Documentation: Incorrect "operationData"

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#130]
See:

https://www.google.com/url?hl=en&q=https://github.com/lime-company/powerauth-webflow/wiki/Next-Step-Server-REST-API-Reference%23create-an-operation&source=gmail&ust=1509028109742000&usg=AFQjCNG50N3N9EXoyUXCrCj1VxbdSc6qyQ

The type of `operationData` is `String`. In our example, the string is accidentally a JSON string. Documentation is missing the surrounding quotes.

**Comment by romanstrobl** [comment]
I fixed the documentation for operationData.
