### ISSUE TITLE
Fix issue with session restart on canceling the auth step

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#14]
Steps to reproduce:

1) Visit the username / password authentication page
2) Click Cancel
3) Retry authentication
=> We always get error response, due to invalid session attributes

**Comment by romanstrobl** [comment]
I cannot reproduce this issue anymore, can we close it?

**Comment by petrdvorak** [comment]
@romanstrobl ... not yet - I can reproduce the issue when using WSO2 IS as a "federated login wrapper". We need to investigate what's going on first...

**Comment by petrdvorak** [comment]
Cannot reproduce. Feel free to reopen.
