### ISSUE TITLE
Invalid response data in /api/auth/init/authenticate

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#170]
Currently, the `/api/auth/init/authenticate` endpoint has following structure:

**Request**
```json
{
        "operationId": null
}
```
**Response**
```json
{
	"result": "CONFIRMED",
	"next": [{
		"authMethod": "USER_ID_ASSIGN",
		"params": []
	}, {
		"authMethod": "USERNAME_PASSWORD_AUTH",
		"params": []
	}],
	"message": null,
	"operationId": "b8a037cf-bdb5-4264-ba8f-b7ff832c50fc"
}
```

The expected structure is:

**Request**
```json
{
}
```
**Response**
```json
{
	"result": "CONFIRMED",
	"next": [{
		"authMethod": "USERNAME_PASSWORD_AUTH",
		"params": []
	}],
	"message": null
}
```

Basically:

- only methods with visual representation should be present
- we should not include operation ID

**Comment by romanstrobl** [comment]
I fixed the second part of the issue related to authentication methods without user interface.
