### ISSUE TITLE
ORA-00972: identifier is too long

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#188]
```
sql> SELECT * from NS_OPERATION WHERE operation_id="62395a78-ad31-4d83-a02d-1c68115270eb"
[2017-11-13 17:59:26] [42000][972] ORA-00972: identifier is too long
```

When working with Oracle DB prior to 12.2, using UUID as identifiers causes issue since the ID is too long (longer than 30, which is SQL-92 standard).

> "No, prior to Oracle version 12.2, identifiers are not allowed to exceed 30 characters in length."
> https://stackoverflow.com/questions/3085562/ora-00972-identifier-is-too-long-alias-column-name

We should either update SQL scripts so that `operation_id` is not a primary index / key, or we should conclude we do not support Oracle DB before 12.2 (whis is an issue, since we would force our customers to upgrade Ora... drop us...)

**Comment by romanstrobl** [comment]
The limit is for column names, should not be related to values.
