### ISSUE TITLE
Isolate data adapter into separate github repository

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#193]
As we started customizing Web Flow for the first client, we had to prepare a private fork of Web Flow. It feels incorrect to have the whole repository used for customization. We should isolate only the data adapter into separate repository, so that we can do all customizations only atop of this single component.

**Comment by romanstrobl** [comment]
See: https://github.com/lime-company/powerauth-webflow-customization

Once we confirm that the content is correct I will remove the Data Adapter project from Web Flow.

**Comment by petrdvorak** [comment]
We should call the folder just `ext-resources` - this is what is used in the deploy scripts / JSPs. The idea is that the client just edits CSS files and messages and copies the folder in either Docker deploy folder or local server storage (`/opt/ext-resources`).

**Comment by romanstrobl** [comment]
Ok, I renamed the folder.

**Comment by petrdvorak** [comment]
Looks OK, closing.
