### ISSUE TITLE
Implement possession signed endpoints with using token based authentication.

### ISSUE THREAD

**Issue by hvge** [lime-company/powerauth-webflow#208]
Recently, we have successfully implemented and tested a token based authentication in our mobile client application, so we should remove that old possesion-signed endpoints and replace them with token based authentication.
* `/api/auth/token/app/push/register` -> currently has token impl. at `/api/auth/token/app/token/push/register`
* `/api/auth/token/app/operation/list` -> currently has token impl. at `/api/auth/token/app/token/operation/list`

As you can see, there are too much "token" in the URL, so we should just use the old URLs with this new token base method for authentication.

**Comment by petrdvorak** [comment]
I agree - I kept the original endpoint so that we can maintain the compatibility for the short period of time when some parts are not yet migrated. Since mToken already  implements token based authentication, the backward compatibility is no longer relevant.
