### ISSUE TITLE
Test application on IE / MS Edge

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#241]
We currently develop in modern browsers, we should also test on legacy systems... #trolling

**Comment by romanstrobl** [comment]
We can support IE9 and higher, React no longer supports IE8, see:

https://reactjs.org/blog/2016/01/12/discontinuing-ie8-support.html

I will test IE9, IE10, IE11 and Edge.

**Comment by romanstrobl** [comment]
Current IE adoption based on https://caniuse.com/usage-table

![image](https://user-images.githubusercontent.com/26658588/33769158-5cc3ee34-dc29-11e7-9410-26c70cd0d2cf.png)
