### ISSUE TITLE
Date and amount formatting by locale

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#245]
We currently localize form keys. For some values, however, we should allow value localization as well. These include date and amount with currency.

Technically, we should introduce new form items for these value types.

(soon post release)

**Comment by romanstrobl** [comment]
We will implement value formatting for following form data attribute types:
* KEY_VALUE
* NOTE

The value formatting will support:
* localization - value gets localized into given locale using message resources
* types:
  * TEXT (not formatted)
  * DATE (formatted in given locale)
  * NUMBER(100,00 vs. 100.00 based on locale)
  * other types may be added later

We will also need to handle formatting and localization for currencies in AMOUNT type (e.g. 100.00 CZK vs. 100,00 Kč). The logic is a bit more complex - the input is amount and currency and formatting differs per locale (e.g. $100 USD vs. 100 Kč).
