### ISSUE TITLE
Avoid using raw "valueOf" when converting enums

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#263]
When using `MyEnum.valueof(someValue)`, the conversion is case sensitive and does not provide any graceful fallback in case value is not found. This caused us issues here:

https://github.com/lime-company/powerauth-webflow/blob/92ce1ed9dff2ab044cb3b956b4d15884155576ce/powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileAppApiController.java#L211

Our customer was sending `unknown` as a reason and therefore, the conversion was failing. We should implement own converter to convert String values to enums.

**Comment by romanstrobl** [comment]
Ok, so the conversion will not be case sensitive and when the value is not recognized, it will default to UNKNOWN, right?

**Comment by petrdvorak** [comment]
Yes
