### ISSUE TITLE
Allow default attributes for dynamic form data

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#279]
Currently, we show the dynamic form data (account picker) anytime account list is fetched for given operation in data adapter. However, we do not allow some basic form features, such as:

- disabling the dynamic picker
- selecting a default value

I suggest extending our form API for creating a new operation in a following way:

```json
{
  "formData": {
    "attributes": [
      {
        "id": "operation.bankAccountChoice",
        "enabled": false,
        "defaultValue": "CZ0012341234123412341234"
      }
    ]
  }
}
```

This would indicate, that form field with ID `operation.bankAccountChoice` should be disabled and should display item that corresponds to the default value `CZ0012341234123412341234`.

_Design choice: Keeping these attributes separate from the form fields can be a subject of discussion - I placed them this way so that the dynamic data can be customized as well._

**Comment by romanstrobl** [comment]
Yes, this would be useful.

**Comment by petrdvorak** [comment]
Let's have a look at this one next...

**Comment by romanstrobl** [comment]
Ok, I am working on it.
