### ISSUE TITLE
Isolate model classes used in mtoken project

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#308]
Currently, we use model objects from Next Step and own model objects. We should isolate the classes so that we make standalone mToken deployments easier.

**Comment by jtomekcz** [comment]
Hello, when I want implements service /api/auth/token/app/operation/list I must use also InvalidActivationException class. This class is not in powerauth-mtoken-model but in powerauth-webflow-authentication-mtoken.
In my project I have added dependency only on powerauth-mtoken-model.
Thank you for your response.

**Comment by petrdvorak** [comment]
I have added error codes in a new [`ErrorCode`](https://github.com/lime-company/powerauth-webflow/blob/55ecc3d1e6ff0546cd30665e0c67a4b888478f97/powerauth-mtoken-model/src/main/java/io/getlime/security/powerauth/lib/mtoken/model/enumeration/ErrorCode.java) class in `powerauth-mtoken-model` Maven module.

**Comment by jtomekcz** [comment]
Hello, OK - exception handling will be resolved on our side. Btw, after added of dependency powerauth-mtoken-model in our project, are all needed POJO,s visible. I thing that your last changes are for our project sufficients.
Thank you so much

**Comment by petrdvorak** [comment]
No problem and I am sorry for the inconvenience. We should have had this isolated module from the very beginning...
