### ISSUE TITLE
Allow some mobile operations to be verified by PIN only

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#310]
Currently, we use Touch ID and Face ID as a substitute for PIN. We should allow PIN only approval.

**Comment by petrdvorak** [comment]
I [extended model of operation returned from the server](https://github.com/lime-company/powerauth-webflow/wiki/Mobile-Token-API#response) with attribute `allowedSignatureType`, so that we are now able to send hint to mobile token app.

**Comment by romanstrobl** [comment]
Already implemented.
