### ISSUE TITLE
Extract operation specific code in DA into separate methods

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#315]
Currently, we have couple unnecessary strings in Data Adapter:

```
login.smsText=Authorization code for login is {0}.
authorize_payment.smsText=Authorization code for payment of {0} {1} to account {2} is {3}.
```

However, these strings may be safely placed in Web Flow I18N project, since they are used in Web Flow component only...

**Comment by romanstrobl** [comment]
I tried to move the resources however I get an exception during Data Adapter startup when I add dependency on powerauth-webflow-i18n and try to use the I18NService: 

```
org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'messageSource' is expected to be of type 'io.getlime.security.powerauth.app.webflow.i18n.ReloadableResourceBundleMessageSourceWithListing' but was actually of type 'org.springframework.context.support.ReloadableResourceBundleMessageSource'
```

I will look into it later.

**Comment by petrdvorak** [comment]
Let's discuss this is person - adding `powerauth-webflow-i18n` as a Data Adapter dependency was not the idea and the more I think about it the more I believe that we should actually keep the resources separated but change DA API a bit (so that customizations do not need to change `SMSPersistenceService` when adding a new operation type).

**Comment by romanstrobl** [comment]
We agreed to keep the resources which are related to Data Adapter in Data Adapter project. We will just separate the logic which prepares the SMS text into a special method, so that it is clear how the logic can be overriden.
