### ISSUE TITLE
Migration guide - use one page per single version

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#342]
Currently, we have one long page for migration guide - see here:

https://github.com/lime-company/powerauth-webflow/wiki/Migration-Instructions

We should probably have separate documents for each version, like here:

https://github.com/lime-company/powerauth-server/wiki/Migration-Instructions

This way, it will be easier for us to link the correct documentation from here:

https://github.com/lime-company/powerauth-crypto/wiki/PowerAuth-2018.03

**Comment by romanstrobl** [comment]
I separated the guides, see:

https://github.com/lime-company/powerauth-webflow/wiki/Web-Flow-0.19.0
https://github.com/lime-company/powerauth-webflow/wiki/Web-Flow-0.20.0
