### ISSUE TITLE
Choose account in authorize step

### ISSUE THREAD

**Issue by romanstrobl** [lime-company/powerauth-webflow#79]
- Add combobox to UI of review step to choose account if multiple accounts are available (for one account combobox is disabled) 
- Save chosen account setting across operation
  - Add new parameter into displayData
  - In second authorization step account cannot be changed
- Add account info into operation when user is known (call Bank Adapter API) 
- Enrich Bank Adapter API to query for accounts per user id

**Comment by petrdvorak** [comment]
We need to implement this in a more generic way, see #86...

**Comment by romanstrobl** [comment]
Chosen account should be saved via displayDetails and stored with operation. We should use fqn names for form data to identify both step and the form item name. We should introduce complex type in displayDetails for choosing account (contains name of account, account number, insufficient limit info, etc.).

Data which is filled in by user during operation should be available for pull (via Next Step DB) and should be also pushed at the moment when the step is performed (right now it is not needed as realtime - only when the form is actually submitted).
