### ISSUE TITLE
Call Data Adapter on operation approval, rejection or cancel

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#85]
We should add API to bank adapter where we can notify other systems whenever operation is approved, rejected or canceled.

**Comment by romanstrobl** [comment]
I started implementing this enhancement. Next Step is the component which knows exactly when such events occur, however Next Step is currently not aware of Bank Adapter - all communication with Bank Adapter happens from authentication methods. We can intercept the operation status change in AuthMethodController - but we need to make sure this is the only place where Next Step's updateOperation() method is called. Currently it is the case, just a note to myself not to forget about this in the future. 

Another options is to make Next Step aware of Bank Adapter, but that would mean adding a new dependency.

**Comment by romanstrobl** [comment]
We agreed not to add the dependency and send notifications from AuthMethodController.
