### ISSUE TITLE
Add support for dynamic form data

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#86]
Currently, the operation review is static page with listed operation data. We should also include support for dynamic data. For example, we need to be able to let user choose source account for the payment.

**Comment by petrdvorak** [comment]
Note: When user selects some dynamic information, it should be posted to bank adapter, so that the external systems are aware of the coice.

**Comment by romanstrobl** [comment]
Diagram of enriching displayData with dynamic data:

![image](https://user-images.githubusercontent.com/26658588/30711323-ada35e6a-9f08-11e7-9b08-995aaa3705cb.png)
